jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build AAR
        run: ./gradlew assembleRelease
      - name: Publish to GitHub Packages
        run: ./gradlew :curvedBottomNavigationLib:publishBarPublicationToGitHubPackagesRepository
